title: Courtsy
description: Free, simple court booking for communities.
url: "https://courtsyapp.com"
baseurl: ""
repository: stankovski/courtsy-website

sass:
  style: compressed

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor
